#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSwaps' function below.
#
# The function accepts INTEGER_ARRAY a as parameter.
#

def countSwaps(a):
    numSwap = 0
    for i in range(len(a) - 1):
        for j in range(len(a) - i - 1):
            if a[j] > a[j + 1]:
                a[j], a[j + 1] = a[j + 1], a[j]
                numSwap += 1
            firstElement = a[0]
            lastElement = a[-1]
                
    print("Array is sorted in {} swaps.".format(numSwap))
    print("First Element: {} ".format(firstElement))
    print("Last Element: {} ".format(lastElement))
if __name__ == '__main__':  
    n = int(input().strip())
    a = list(map(int, input().rstrip().split()))

    countSwaps(a)
